### PR TITLE
Release Ubuntu Jammy Jellyfish

### PR DESCRIPTION
**Pull request by darkdragon-001**

### CODE REVIEW

**Comment by toabctl** [comment]
The current Jammy container is not up-to-date. We are in the process to update the container and then we'll do the switch. So don't merge this.

**Comment by tianon** [comment]
I would recommend waiting to merge this until jammy is GA unless you are certain that you won't need to update the image before the release officially happens.

**Comment by tianon** [comment]
... and there's the release :joy:

**Comment by toabctl** [comment]
@tianon https://github.com/docker-library/official-images/pull/12279 is the update for the official images.

**Comment by tianon** [comment]
So this should be merged now and verified that the output matches that, right?

**Comment by toabctl** [comment]
> So this should be merged now and verified that the output matches that, right?

yes. merging.

**Pull request merged**
