### PR TITLE
Move bionic, focal, groovy and hirsute to OCI tarballs

### PR DESCRIPTION
**Pull request by toabctl**
This is a follow up on 26b6ae75425961 . There are now tarballs on
https://partner-images.canonical.com/oci/ also for bionic, focal,
groovy and hirsute so use theses new tarballs.

### CODE REVIEW

**Comment by toabctl** [comment]
cc @mwhudson

**Comment by mwhudson** [comment]
I think we need i386 images for bionic?

**Comment by toabctl** [comment]
> I think we need i386 images for bionic?

good catch. Working on it now.

**Comment by toabctl** [comment]
Done now. Bionic i386 available at https://partner-images.canonical.com/oci/bionic/current/

**Comment by mwhudson** [comment]
LGTM -- @tianon?

**Pull request merged**
