### PR TITLE
rolling is now hirsute

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by tianon** [comment]
Rolling suit?

image

LGTM :smile:

**Comment by alex** [comment]
😂 is there anything else I can do to help roll this into the official image tags?

**Comment by tianon** [comment]
I guess it's been ~20 days since https://github.com/docker-library/official-images/blob/master/library/ubuntu was updated, so it seems pretty reasonable to me to do a bump for this (esp. since Hirsute is now released).

I'm hoping https://partner-images.canonical.com/core/hirsute/current/ is up-to-date with the latest and greatest from today's release?

**Comment by tianon** [comment]
https://doi-janky.infosiftr.net/job/tianon/job/update-ubuntu/94/ heh, looks like @philroche has beat us to the punch :smile:

**Comment by tianon** [comment]
(although it probably needs a kick since it looks like that ran before this merged)

**Comment by tianon** [comment]
(or I guess this part happens separately, nevermind me -- full steam ahead, @philroche)

**Review by philroche — COMMENTED** [review]
Post merge +1. Thanks @alex

**Review by lioncorpo — COMMENTED** [review]
Thanks

**Pull request merged**
