### PR TITLE
Rollback recent update to Ubuntu 14.04 Trusty

### PR DESCRIPTION
**Pull request by philroche**
Due to issues updating and installing packages when ESM repo is added
we are rolling back recent update to Trusty.

For more context see discussions in https://github.com/docker-library/official-images/pull/7029

Until either the build process if updated or the ubuntu-advantage-tools package is fixed we
need to avoid pushing out any new Trusty images.

### CODE REVIEW

**Comment by tianon** [comment]
IMO we should leave the "rollback" as the manual patch we're doing in https://github.com/docker-library/official-images/pull/7038 because the long-term goal is to fix the image and get it published, right?  So I think we should focus on getting the tarballs fixed, do a bit deeper verification of them this time, and just do a proper update.

**Comment by philroche** [comment]
Understood. My concern was if we happen to push out a new image before the long-term fix is completed.

**Comment by tianon** [comment]
This is fixed now, right?

**Comment by philroche** [comment]
Yes. We can close

**Pull request closed without merging**
